config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'items#index'
  mount ActionCable.server => "/cable"
  resources :credits, only: %i[index new create destroy]
  resources :items, only: %i[index new create show edit update destroy] do
    resources :comments, only: :create
    collection do
      get 'search'
      get 'incremental'
      get 'ransack'
    end
    resources :buy_histories, only: %i[new create]
  end
  resources :users, only: %i[new show edit update] do
    member do
      get 'identification'
      get 'logout'
    end
    collection do
      get 'check'
    end
  end
  
end

app/views/shared/_error_messages.html.haml
- if model.errors.any?
  .alert-messages
    %ul
      - model.errors.full_messages.each do |message|
        %li
          = message

app/views/shared/_flash_messages.html.haml
.flash-message
  - flash.each do |type, msg|
    - type = 'info' if type == 'notice'
    - type = 'error' if type == 'alert'
    :erb
      <script>
        toastr.options = {
          "closeButton": false,
          "debug": false,
          "newestOnTop": false,
          "progressBar": false,
          "positionClass": "toast-top-full-width",
          "preventDuplicates": false,
          "onclick": null,
          "showDuration": "300",
          "hideDuration": "1000",
          "timeOut": "3000",
          "extendedTimeOut": "1000",
          "showEasing": "swing",
          "hideEasing": "linear",
          "showMethod": "fadeIn",
          "hideMethod": "fadeOut"
        }
        toastr['<%= type %>']('<%= msg %>');
      </script>

app/views/shared/_footer.html.haml
%footer.top-page-footer
  .app-banner
    .app-banner__contents
      %h3
        スマホでかんたんフリマアプリ
      %h2
        今すぐ無料ダウンロード！
      .app-banner__contents__icons
        .app-banner__contents__icons__mercari
          = image_tag "mercari_icon.png"
        .app-banner__contents__icons__apple-store
          = image_tag "app-store.svg"
        .app-banner__contents__icons__google-play
          = image_tag "google-play.svg"
    .app-banner__app-image
      = image_tag "download_content_pc.png"
  .global-footer
    .about
      %h3 メルカリについて
      %ul
        %li 会社概要（運営会社）
        %li 採用情報
        %li プレスリリース
        %li 公式ブログ
        %li メルカリロゴ利用ガイドライン
      .about__social-icon
        .about__social-icon--sns-twitter
          = fa_icon "twitter"
        .about__social-icon--sns-facebook
          = fa_icon "facebook-square"
    .help
      %h3 ヘルプ＆ガイド
      %ul
        %li メルカリガイド
        %li らくらくメルカリ便
        %li ゆうゆうメルカリ便
        %li 大型メルカリ便
        %li 車体取引ガイド
        %li メルカリあんしん・あんぜん宣言！
        %li 偽ブランド品撲滅への取り組み
        %li メルカリボックス
    .privacy
      %h3 プライバシーと利用規約
      .privacy__list
        %ul
          %li プライバシーポリシー
          %li メルカリ利用規約
          %li あんしんスマホサポート制度に関する利用特約
          %li コンプライアンスポリシー
        %ul
          %li 個人データの安全管理に係る基本方針
          %li 特定商取引に関する表記！
          %li 資金決済法に基づく表示
          %li 法令順守と犯罪抑止のために
          %li 返品・返金ポリシー
    .language
      %h3 国
      %ul
        %li 日本
        %li United States
  .bottom-footer
    .bottom-footer__image
      = image_tag "logo-white.svg"
    .bottom-footer__trademark
      © 2019 Mercari

app/views/shared/_header.html.haml
%header.page_header
  .header_container
    .header_container_top
      .header_container_top_left
        = link_to root_path do
          = image_tag "logo.svg"
      .header_container_top_right
        - if controller.controller_name == "items" && action_name == "search"
          = form_with url: incremental_items_path ,method: :get ,class: "header_search" do |f| 
            = f.text_field :keyword ,{class: "header_search__input incremental", placeholder: "何かお探しですか？"}
        - else
          = form_with url: search_items_path ,local: true, method: :get ,class: "header_search" do |f| 
            = f.text_field :keyword ,{class: "header_search__input", placeholder: "何かお探しですか？"}
            = f.label :search, {class: "search_label"} do
              = fa_icon "search"
            = f.submit "送信", {class: "header_search__submit", id: "search"}        
    .header_container_bottom
      .header_container_bottom__category
        = render "shared/header_category"
      .header_container_bottom__bland
        %p
          = fa_icon "tag"
          ブランドから探す
        %ul.header_container_bottom__bland_list
          %li シャネル
          %li ナイキ
          %li ルイヴィトン
          %li シュプリーム
          %li アディダス
          %li ブランド一覧
      .header_container_bottom__center
      - if user_signed_in?
        .header_container_bottom__info
          = link_to user_path(current_user) do
            %p
              = fa_icon "bell-o"
              お知らせ
          %ul.header_container_bottom__info_list
            - 4.times do |i|
              %li
                = image_tag "mercari_profile.png"
                .header_info__msg
                  チケットがあります
                  .header_info__msg__time
                    = fa_icon "clock-o"
                    2時間前
                .header_info__chevrson_right
                  = fa_icon "chevron-right"
        .header_container_bottom__todo
          = link_to user_path(current_user) do
            %p
              = fa_icon "check"
              やることリスト
          .header_container_bottom__todo_list
        .header_container_bottom__mypage
          %p
            = link_to "マイページ", user_path(current_user)
          .header_container_bottom__mypage_image
            = image_tag "member_photo_noimage_thumb.png"
          .header_container_bottom__mypage_overview
            .overview_background
              .user_image
                = image_tag "member_photo_noimage_thumb.png"
            .overview_main
              .overview_main__top
                = current_user.nickname if user_signed_in?
                .achievement
                  %span 評価: 11
                  %span 出品数: 20
              .overview_main__top
                %ul.stock_money_list
                  %li
                    残高
                    %span
                      ￥800
                      = fa_icon "chevron-right"
                  %li
                    ポイント
                    %span 
                      P2000
                      = fa_icon "chevron-right"
            .overview_lists
              %ul
                %li.overview_list
                  いいね一覧
                  %span
                    = fa_icon "chevron-right"
                = link_to "#" do
                  %li.overview_list
                    出品した商品 - 出品中
                    %span
                      = fa_icon "chevron-right"
                %li.overview_list
                  出品した商品 - 取引中
                  %span
                    = fa_icon "chevron-right"
                %li.overview_list
                  出品した商品 - 売却済
                  %span
                    = fa_icon "chevron-right"
                %li.overview_list 
                  購入した商品 - 取引中
                  %span
                    = fa_icon "chevron-right"
                %li.overview_list
                  購入した商品 - 購入済
                  %span
                    = fa_icon "chevron-right"
      - else 
        .header_container_bottom__new_user
          = link_to "新規会員登録", new_user_path, class: "registration"
          = link_to "ログイン", new_user_session_path, class: "session"

app/views/shared/_header_category.html.haml
%p
  = fa_icon "list"
  カテゴリーから探す
%ul.header_container_bottom__category_list1
  - Category.where('id < 14').each do |category|
    %li.category_list_item{data: {id: category.id}}
      = category.name
      %ul
        - Category.where(category_id: category.id).each do |child_category|
          %li.category_list_item{data: {id: child_category.id}}
            = child_category.name
            %ul
              - Category.where(category_id: child_category.id).each_with_index do |grandchild_category, index|
                %li.category_list_item{data: {id: grandchild_category.id}}
                  = grandchild_category.name
                - if index == 18
                  - break

-# %ul.header_category_box
-#   %li aaaa

app/views/shared/_my_page_sidebar.html.haml
%ul.menu-list.list-parent
  = link_to user_path(current_user) , class: "active_link" do
    %li.menu-list__item.list-item
      マイページ
      = fa_icon "chevron-right",class:"menu-list__item__arrow"
  %li.menu-list__item.list-item
    お知らせ
    = fa_icon "chevron-right",class:"menu-list__item__arrow"
  %li.menu-list__item.list-item
    やることリスト
    = fa_icon "chevron-right",class:"menu-list__item__arrow"
  %li.menu-list__item.list-item
    いいね！一覧
    = fa_icon "chevron-right",class:"menu-list__item__arrow"
  = link_to new_item_path , class: "active_link" do
    %li.menu-list__item.list-item
      出品する
      = fa_icon "chevron-right",class:"menu-list__item__arrow"
  %li.menu-list__item.list-item
    出品した商品 - 出品中
    = fa_icon "chevron-right",class:"menu-list__item__arrow"
  %li.menu-list__item.list-item
    出品した商品 - 取引中
    = fa_icon "chevron-right",class:"menu-list__item__arrow"
  %li.menu-list__item.list-item
    出品した商品 - 売却済み
    = fa_icon "chevron-right",class:"menu-list__item__arrow"
  %li.menu-list__item.list-item
    購入した商品 - 取引中
    = fa_icon "chevron-right",class:"menu-list__item__arrow"
  %li.menu-list__item.list-item
    購入した商品 - 過去の取引
    = fa_icon "chevron-right",class:"menu-list__item__arrow"
  %li.menu-list__item.list-item
    ニュース一覧
    = fa_icon "chevron-right",class:"menu-list__item__arrow"
  %li.menu-list__item.list-item
    評価一覧
    = fa_icon "chevron-right",class:"menu-list__item__arrow"
  %li.menu-list__item.list-item
    ガイド
    = fa_icon "chevron-right",class:"menu-list__item__arrow"
  %li.menu-list__item.list-item
    お問い合わせ
    = fa_icon "chevron-right",class:"menu-list__item__arrow"
%h3
  メルペイ
%ul.melpay.list-parent
  %li.melpay__item.list-item
    売り上げ・振込申請
    = fa_icon "chevron-right",class:"menu-list__item__arrow"
  %li.melpay__item.list-item
    ポイント
    = fa_icon "chevron-right",class:"menu-list__item__arrow"
%h3
  設定
%ul.setting.list-parent
  = link_to edit_user_path(current_user) , class: "active_link" do
    %li.setting__item.list-item
      プロフィール
      = fa_icon "chevron-right",class:"menu-list__item__arrow"
  %li.setting__item.list-item
    発送元・お届け先住所変更
    = fa_icon "chevron-right",class:"menu-list__item__arrow"
  = link_to credits_path , class: "active_link" do
    %li.setting__item.list-item
      支払い方法
      = fa_icon "chevron-right",class:"menu-list__item__arrow"
  %li.setting__item.list-item
    メール/パスワード
    = fa_icon "chevron-right",class:"menu-list__item__arrow"
  = link_to identification_user_path(current_user) , class: "active_link" do
    %li.setting__item.list-item
      本人情報
      = fa_icon "chevron-right",class:"menu-list__item__arrow"
  %li.setting__item.list-item
    電話番号の確認
    = fa_icon "chevron-right",class:"menu-list__item__arrow"
  = link_to logout_user_path(current_user) , class: "active_link" do 
    %li.setting__item.list-item
      ログアウト
      = fa_icon "chevron-right",class:"menu-list__item__arrow"

app/views/shared/_new_item_button.html.haml
.new_item_button
  = link_to new_item_path do
    .new_item_button__content
      %p 出品
      = fa_icon "camera"
    

app/views/shared/_new_signup_footer.html.haml
%footer.new_signup_footer
  .new_signup_footer__cautions
  %p
    %a プライバシーポリシー
    %a メルカリ利用規約
    %a 特定商取引に関する表示

  .new_signup_footer__img 
    = image_tag "logo-gray.svg"
  %p
    %a © 2019 Mercari

app/views/shared/_payment_form.html.haml
= form_with model: Credit.new, method: :post,url: credits_path,local: true,class: "payment_form" do |f|
  %p 
    カード番号
    %span.required_red 必須
  = f.text_field :number, {class: "credit_number_input", placeholder: "半角数字のみ", maxlength: "16"}
  .mercari_payment_image
    = image_tag "mercari_payment_image.png"
  %p
    有効期限
    %span.required_red 必須
  .payment_expiry
    .payment_expiry__box
      = f.select :month, {}
      %p 月
      = fa_icon "chevron-down", class: "chevron_down"
    .payment_expiry__box
      = f.select :year, {}
      %p 年
      = fa_icon "chevron-down", class: "chevron_down"
  %p
    セキュリティコード
    %span.required_red 必須
  .payment_expiry__security_input
    = f.text_field :security, {class: "security_input", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4"}
  .payment_description
    = fa_icon "question-circle"
    %span カード背面の番号とは?
    = image_tag "credit_back.png", class: "credit_back_img"
  = f.submit "次へ進む", class: "payment_submit"
    

app/views/shared/_top_page_main.html.haml
.top_page_main_container
  .pick_up_category.wrapper
    %h1 ピックアップカテゴリー
    .categocies.main_block
      .pick_up_category_ladies.main_block_new_items
        %h2
          = link_to "レディース 新着アイテム", "#"
        .main_block_new_items_area
          - if @ladies
            - @items = @ladies
            = render @items
      .pick_up_category_mens.main_block_new_items
        %h2
          = link_to "メンズ 新着アイテム", "#"
        .main_block_new_items_area
          - if @mens
            - @items = @mens
            = render @items
      .pick_up_category_mens.main_block_new_items
        %h2
          = link_to "新着アイテム", "#"
        .main_block_new_items_area
          - if @latest_items
            - @items = @latest_items
            = render @items