config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'items#index'
  mount ActionCable.server => "/cable"
  resources :credits, only: %i[index new create destroy]
  resources :items, only: %i[index new create show edit update destroy] do
    resources :comments, only: :create
    collection do
      get 'search'
      get 'incremental'
      get 'ransack'
    end
    resources :buy_histories, only: %i[new create]
  end
  resources :users, only: %i[new show edit update] do
    member do
      get 'identification'
      get 'logout'
    end
    collection do
      get 'check'
    end
  end
  
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
  validates :customer_id, presence: true
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  def index
    if current_user.credits.present?
      Payjp.api_key = get_payjp_key
      credit = current_user.credits.first
      customer = Payjp::Customer.retrieve(credit.customer_id)
      card = customer.cards.retrieve(customer.default_card)
      @card_info = get_card_info(current_user)
    end
  end

  def new
    redirect_to credits_path if current_user.credits.present?
  end

  def create
    if current_user.credits.present?
      redirect_to credits_path
    else
      Payjp.api_key = get_payjp_key
      customer = Payjp::Customer.create
      @credit = create_payjp_card(current_user, customer)
      if @credit.save
        flash[:notice] = "クレジットカードを登録しました"
        redirect_to credits_path
      else
        flash[:alert] = "登録に失敗しました"
        render "new"
      end
    end
  end

  def destroy
    if current_user.credits.present?
      Payjp.api_key = get_payjp_key
      credit = current_user.credits.first
      customer = Payjp::Customer.retrieve(credit.customer_id)
      customer.delete
      credit.destroy
      flash[:notice] = "クレジットカードを削除しました"
    end
    redirect_to credits_path
  end

  private

  def create_payjp_customer
    Payjp.api_key = get_payjp_key
    customer = Payjp::Customer.create
  end

  def create_payjp_card(user, customer)
    customer.cards.create(card: token_parmas[:token])
    credit = Credit.new(
      user_id: user.id,
      customer_id: customer.id
    )
  end

  def token_parmas
    params.permit(:token)
  end

  def get_payjp_key
    Rails.application.credentials.MERUCARI_PAYJP_SECRET_KEY
  end

  def get_card_info(user)
    Payjp.api_key = get_payjp_key
    credit = user.credits.first
    customer = Payjp::Customer.retrieve(credit.customer_id)
    card = customer.cards.retrieve(customer.default_card)
    card_info = {}
    card_info[:brand] = if card.brand == "Visa"
                          "visa.svg"
                        elsif card.brand == "master"
                          "master.png"
                        elsif card.brand == "jcb"
                          "jcb.png"
                        else
                          "non-card.png"
                        end

    card_info[:last4] = "*" * 12 + card.last4
    card_info[:exp_date] = "#{card.exp_month}/#{card.exp_year.to_s.slice(2, 2)}"
    card_info
  end

  def pay(user, item)
    return false if user.nil? || item.nil? || user.credits.blank?

    Payjp.api_key = get_payjp_key
    charge = Payjp::Charge.create(
      amount: item.price,
      customer: user.credits.first.customer_id,
      currency: 'jpy'
    )
    true
  end
end

app/views/credits/index.html.haml
.user-my-page
  = render "shared/header"
  .bread
    %span 
      - breadcrumb :credit
      = breadcrumbs separator: " #{content_tag(:i, '', class:'fa fa-chevron-right')} "
  .container
    .left-column
      = render "shared/my_page_sidebar"
    .right-column
      .select-payment
        .select-payment__header
          支払い方法
        .select-payment__contents
          %h2 クレジットカード一覧
          - if @card_info.nil?
            = link_to new_credit_path, class: "new_credit_btn" do
              = fa_icon "credit-card"
              クレジットカードを追加する
          - else
            .select-payment__contents__card
              .select-payment__contents__card__data
                = image_tag @card_info[:brand]
                %p
                  = @card_info[:last4]
                %p
                  = @card_info[:exp_date]
              .select-payment__contents__card__link
                = link_to credit_path(current_user), method: :delete do
                  %p 削除する
          .select-payment__contents__bar
        .select-payment__footer
          = link_to "#" do
            支払い方法について
            = fa_icon "angle-right"
        
  = render "shared/footer"
  = render "shared/new_item_button"

app/views/credits/new.html.haml
.user-my-page
  = render "shared/header"
  .container
    .left-column
      = render "shared/my_page_sidebar"
    .right-column
      .new-card
        .new-card__header
          クレジットカード情報入力
        = render 'shared/payment_form'
  = render "shared/footer"
  = render "shared/new_item_button"