config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'items#index'
  mount ActionCable.server => "/cable"
  resources :credits, only: %i[index new create destroy]
  resources :items, only: %i[index new create show edit update destroy] do
    resources :comments, only: :create
    collection do
      get 'search'
      get 'incremental'
      get 'ransack'
    end
    resources :buy_histories, only: %i[new create]
  end
  resources :users, only: %i[new show edit update] do
    member do
      get 'identification'
      get 'logout'
    end
    collection do
      get 'check'
    end
  end
  
end

app/models/buy_history.rb
class BuyHistory < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/controllers/buy_histories_controller.rb
class BuyHistoriesController < CreditsController
  before_action :set_item

  def new
    redirect_to item_path(@item) if @item.buy_history.present?

    @card_info = get_card_info(current_user) if current_user.credits.present?
  end

  def create
    @buy_history = BuyHistory.new(
      user_id: current_user.id,
      item_id: @item.id
    )
    if pay(current_user, @item) && @buy_history.save
      redirect_to item_path(@item)
    else
      render "new"
    end
  end

  private

  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/views/buy_histories/new.html.haml
.purchase_confirmation_page
  .purchase_confirmation_page_container
    .purchase_confirmation_page_container_header
      .purchase_confirmation_page_container_header__img
        = link_to root_path do
          = image_tag "logo.svg"
    .purchase_confirmation_page_container_main
      .purchase_confirmation_page_container_main_title
        購入内容の確認
      .purchase_confirmation_page_container_main_price
        .price_container
          .price_container_title
          .price_container_item
            = image_tag @item.images[0]
            .item_name
              = @item.name
          .price_container_price
            %span.price_container_price__display
              ="¥#{@item.price}"
            %span.price_container_price__shipping_fee
              送料込み
          .price_container_point
            .no_point ポイントはありません
          .price_container_pay_money
            .price_container_pay_money__title
              お支払金額
            .price_container_pay_money__display
              = "¥#{@item.price}"
          - if @card_info.nil?
            .price_container_purchase_button.disable_buy_btn#pay_button
              購入する
          - else 
            .price_container_purchase_button
              = link_to item_buy_histories_path, method: :post do
                購入する
      .purchase_confirmation_page_container_main_delivery_destination
        .delivery_destination_container
          .delivery_destination_container__title
            配送先
          .delivery_destination_container__address
            .delivery_destination_container__address--post_number
              〒 000-0000
            .delivery_destination_container__address--place
              福岡県福岡市天神スーパーハイツ503号室
            .delivery_destination_container__address--purchaser
              ryuji
          = link_to "#", class: "change" do
            変更する
            = fa_icon "chevron-right"
      .purchase_confirmation_page_container_main_delivery_payment 
        .delivery_payment_container
          .delivery_payment_container__title
            支払方法
          - if @card_info.nil?
            %p /
            = link_to "#", class: "change" do
              変更する
              = fa_icon "chevron-right"
          - else
            .delivery_payment_container__credit--number
              = @card_info[:last4]
            .delivery_payment_container__credit--using_period
              = @card_info[:exp_date]
            .delivery_payment_container__credit--image
              = image_tag @card_info[:brand]
            = link_to "#", class: "change" do
              変更する
              = fa_icon "chevron-right"
    = render 'shared/new_signup_footer'