config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'items#index'
  mount ActionCable.server => "/cable"
  resources :credits, only: %i[index new create destroy]
  resources :items, only: %i[index new create show edit update destroy] do
    resources :comments, only: :create
    collection do
      get 'search'
      get 'incremental'
      get 'ransack'
    end
    resources :buy_histories, only: %i[new create]
  end
  resources :users, only: %i[new show edit update] do
    member do
      get 'identification'
      get 'logout'
    end
    collection do
      get 'check'
    end
  end
  
end

app/models/item.rb
class Item < ApplicationRecord
  has_one :buy_history
  belongs_to :user
  has_many :comments
  has_many_attached :images
  belongs_to :category
  has_many :item_images
  accepts_nested_attributes_for :item_images, allow_destroy: true, update_only: true
  # accepts_nested_attributes_for :item_images, allow_destroy: true, update_only: true, reject_if: :reject_images
  # def reject_images(images_attributes)
  #   images_attributes.src.blank?
  # end

  validates :name, presence: true, length: { maximum: 40 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :status, presence: true
  validates :delivery_burden, presence: true
  validates :delivery_method, presence: true
  validates :delivery_prefecture, presence: true
  validates :delivery_time, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999 }

  validate :images_validation


  def images_validation
    if self.images.attached?
      errors.add(:images, "画像の枚数は最大10枚までです。") if images.length > 10
      byte_sum = 0
      images.each do |image|
        errors.add(:images, "#{image.filename}: 画像のサイズは最大3Mまでです。") if image.blob.byte_size > (3 * 1024 * 1024)

        errors.add(:images, "#{image.content_type}: 画像のフォーマットではありません。") unless image.content_type.starts_with?('image/')
        byte_sum += image.blob.byte_size
      end

      errors.add(:images, "画像のサイズは最大(合計)15Mまでです。") if byte_sum > (15 * 1024 * 1024)
    else
      errors.add(:images, ": 画像が1枚以上必要です")
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_item, except: %i[index create new search incremental ransack]

  def index
    @latest_items = Item.limit(20).order("id DESC")
    @ladies = item_list(1)
    @mens = item_list(2)
  end

  def new
    @prefectures = Prefecture.all
    @item = Item.new
    @item.item_images.build
    @parent_categories = Category.where('id < 14')
    @child_categories = Category.where(category_id: params[:keyword])

    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
    @item.item_images.build
    redirect_to item_path(@item) if current_user.id != @item.user.id
  end

  def create
    @item = Item.new(item_params)
    if params[:item][:images].present? && @item.save!
      flash[:notice] = "商品を出品しました！"
      redirect_to root_path
    else
      flash[:alert] = "商品を出品できませんでした"
      render "new"
    end
  end

  def show
    @items = Item.limit(4).order("id DESC")
    @comments = Comment.where(item_id: @item.id)
    @comment = Comment.new
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @item.destroy if @item.user.id == current_user.id
    flash[:notice] = "商品を削除しました"
    redirect_to root_path
  end

  def preview
    @items = current_user.items
  end

  def search
    @keyword = keyword_params[:keyword]
    @items = Item.where('name LIKE(?)', "%#{@keyword}%")
    @q = Item.ransack(params[:q])
  end

  def ransack
    @keyword = params[:q].values[0]
    @q = Item.ransack(search_params)
    @items = @q.result.includes(:category)
    render :search
  end

  def incremental
    @keyword = keyword_params[:keyword]
    @items = []
    @items.push(Item.where('name LIKE(?)', "%#{@keyword}%"))
    if @keyword.to_i > 0
      @items.push(Item.where('price = ?', @keyword.to_i))
      @items.push(Item.where('price < ? ', @keyword.to_i).where('price > ? ', @keyword.to_i * 0.9).limit(10))
    end
    @items.flatten!
    @items.uniq!
    respond_to do |format|
      format.json {}
    end
  end

  private

  def keyword_params
    params.permit(:keyword)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    _params = params.require(:item).permit(
      :name,
      :price,
      :description,
      :status,
      :delivery_burden,
      :delivery_method,
      :delivery_prefecture,
      :delivery_time,
      :size,
      :category_id,
      item_images_attributes: [:src, :_destroy, :id]
    ).merge(user_id: current_user.id)
    
    if params[:item][:images].present?
      _params.merge!(images: images_params)
    end
    _params
  end

  def images_params
    strong_param = params.require(:item).permit(images: [])
    if strong_param[:images].present?
      strong_param[:images].each do |image|
        image.original_filename = URI.encode(image.original_filename)
      end
    end
    strong_param[:images]
  end

  def remove_images_params
    params.require(:item).permit(remove_images: [])
  end

  def item_list(i)
    item_array = []
    Item.find_each do |item|
      category_id = item.category.parent.parent.id
      item_array.push(item) if category_id == i
    end
    array_length = item_array.length
    item_array.slice!(-4, 4)
  end

  def search_params
    params.require(:q).permit!
  end
end

app/views/items/_item.html.haml
- if item.buy_history.present?
  = link_to item, class: "one_item item_soldout__parent search_item" do
    .one_item__image_area.item_soldout__children
      = image_tag item.images[0]
    .one_item__text_area
      .one_item__text_area--title
        = item.name
      .one_item__text_area--price
        = "¥#{item.price}"
        %span
          = fa_icon "heart-o"
          8
- else 
  = link_to item, class: "one_item search_item" do
    .one_item__image_area
      = image_tag item.images[0]
    .one_item__text_area
      .one_item__text_area--title
        = item.name
      .one_item__text_area--price
        = "¥#{item.price}"
        %span
          = fa_icon "heart-o"
          8

app/views/items/edit.html.haml
.new_item_page
  .new_item_page_container
    .new_item_page_container_top
      .new_item_page_container_top__img
        = link_to root_path do
          = image_tag "logo.svg"
    = form_with model: @item, url: item_path, class: "new_item_page_container_main" ,method: :patch , local: true do |f|
      .new_item_page_container_main_title
        商品の情報を入力
      .new_item_page_container_main_item_image
        = render "shared/error_messages" , model: f.object
        %p.new_item_page_container_main_label
          出品画像
          %span.required
            必須
        %p.desc 最大10枚までアップロードできます。
        .new_item_page_container_main_item_image_area
          .top_area.prepend_area
            - @item.images.each_with_index do |image, index|
              .select_image{data: {number: index}}
                = image_tag image, id: "image_preview"
                %p
                  = link_to "編集", ""
                %p
                  = link_to "削除", "javascript:void(0)", class: "remove_image edit_image_remove"
            .image_file_area
              %p 
                ドラッグアンドドロップ
                %br
                もしくはクリックをしてアップロード
              = f.file_field :images, multiple: true, id: "upload_file", class: "upload_files", data:{id: "1"}, accept: "image/png, image/jpeg, image/gif"
              = f.hidden_field :file, class: "item_images_hidden", multiple: true, value: ""
          .under_area.prepend_area
            .image_file_area
              %p 
                ドラッグアンドドロップ
                %br
                もしくはクリックをしてアップロード
      
      .new_item_page_container_main_carrierwave_image
        %p.new_item_page_container_main_label
          Carrirwaveの場合
        - @item.item_images.each do |image|
          = image_tag image.src.url, width: 100 if image.persisted?
        = f.label :_, {for: "item_item_images_attributes_1_src"} do
          .image_file_area
        = f.fields_for :item_images do |i|
          = i.file_field :src
          = i.check_box :_destroy if i.object.persisted?


      .new_item_page_container_main_item_description
        %p.new_item_page_container_main_label
          商品名 
          %span.required
            必須
        = f.text_field :name, {placeholder: "商品名 (必須40文字まで)", maxlength: "40"}
        %p.new_item_page_container_main_label
          商品の説明
          %span.required
            必須
        = f.text_area :description, {maxlength: "1000",  placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"}
      .new_item_page_container_main_item_detail
        .left_content
          商品の詳細
        .right_content
          %p.new_item_page_container_main_label
            カテゴリ
            %span.required
              必須
          .select_box.category1.edit_category1
            = f.select :category1, options_from_collection_for_select(Category.where(category_id: @item.category.parent.parent.category_id), :id, :name)
            = f.hidden_field :category_parent, value: @item.category.parent.parent.id
            = fa_icon "angle-down"
          .select_box.category2{style: "display: block"}
            = f.select :category2, options_from_collection_for_select(Category.where(category_id: @item.category.parent.category_id), :id, :name)
            = fa_icon "angle-down"
          .select_box.category3{style: "display: block"}
            = f.select :category_id, options_from_collection_for_select(Category.where(category_id: @item.category.category_id), :id, :name)
            = fa_icon "angle-down"
          #select_size
            %p.new_item_page_container_main_label.select_label
              サイズ
              %span.required
                必須
            .select_box
              = f.select :size, [["---", ""], ["XXS以下", "XXS以下"],["XS(SS)", "XS(SS)"], ["S", "S"], ["M", "M"], ["L", "L"], ["XL(LL)", "XL(LL)"], ["2XL(3L)", "2XL(3L)"], ["3XL(4L)", "3XL(4L)"], ["4XL(5L)以上", "4XL(5L)以上"], ["FREE SIZE", "FREE SIZE"]]
              = fa_icon "angle-down"
          #input_bland
            %p.new_item_page_container_main_label.select_label
              ブランド
              %span.optional
                任意
            .input_box
              = f.text_field :bland, {placeholder: "例) シャネル"}
          %p.new_item_page_container_main_label.select_label
            商品の状態
            %span.required
              必須
          .select_box
            = f.select :status, [["---", ""],["新品", "新品"],["未使用に近い", "未使用に近い"],["目立った傷や汚れなし", "目立った傷や汚れなし"], ["やや傷や汚れあり", "やや傷や汚れあり"], ["全体的に状態が悪い", "全体的に状態が悪い"]]
            = fa_icon "angle-down"
      .new_item_page_container_main_item_delivary
        .left_content
          配送について
        .right_content
          %p.new_item_page_container_main_label
            配送料の負担
            %span.required
              必須
          .select_box
            = f.select :delivery_burden, [["---", ""], ["送料込み(出品者負担)", "送料込み(出品者負担)"],["着払い(購入者負担)", "着払い(購入者負担)"]]
            = fa_icon "angle-down"
          - if @item.delivery_burden == "送料込み(出品者負担)"
            %p.new_item_page_container_main_label.delivery_method_select_label{style: "display: block"}
              配送の方法
              %span.required
                必須
            .select_box.delivery_method_select{style: "display: block"}
              = f.select :delivery_method, [["---", ""], ["未定", ""], ["らくらくメルカリ便", "らくらくメルカリ便"], ["ゆうメール", "ゆうメール"], ["レターパック", "レターパック"], ["普通郵便(定型、定形外)", "普通郵便(定型、定形外)"], ["クロネコヤマト", "クロネコヤマト"], ["ゆうパック", "ゆうパック"], ["クリックポスト", "クリックポスト"], ["ゆうパケット", "ゆうパケット"]], id: "delivery_method"
              = fa_icon "angle-down"
          - else
            %p.new_item_page_container_main_label.delivery_method_select_label{style: "display: block", }
              配送の方法
              %span.required
                必須
            .select_box.delivery_method_select{style: "display: block"}
              = f.select :delivery_method, [["---", ""], ["未定", ""], ["クロネコヤマト", "クロネコヤマト"], ["ゆうパック", "ゆうパック"], ["ゆうメール", "ゆうメール"]], id: "delivery_method"
              = fa_icon "angle-down"
          %p.new_item_page_container_main_label
            発送元の地域
            %span.required
              必須
          .select_box
            = f.select :delivery_prefecture, options_from_collection_for_select(Prefecture.all, :name, :name)
            = fa_icon "angle-down"
          %p.new_item_page_container_main_label
            発送までの日数
            %span.required
              必須
          .select_box
            = f.select :delivery_time, [["---", ""], ["1~2日", "1~2日"],["3~4日", "3~4日"],["4~7日", "4~7日"]]
            = fa_icon "angle-down"
      .new_item_page_container_main_item_price
        .left_content
          販売価格
          %span (300〜9,999,999)
        .right_content
          .input_price
            %p.new_item_page_container_main_label
              価格
              %span.required
                必須
            .input_price__area
              ¥
              = f.text_field :price, {id: "price", class: "edit_item", placeholder: "例）300", maxlength: "7"}
          .sales_fee
            %p 販売手数料(10%)
            %p.sales_fee__computed.edit_page_fee -
          .sales_benefit
            %p 販売利益
            %p.sales_benefit__computed.edit_page_benefit -
      .new_item_page_container_main_submit
        %p.new_item_page_container_main_submit__attension
          = link_to "禁止されている出品", "#"
          、
          = link_to "行為", "#"
          を必ずご確認ください。
          %br
            またブランド品でシリアルナンバー等がある場合はご記載ください。
            = link_to "偽ブランドの販売", "#"
            は犯罪であり処罰される可能性があります。
            %br 
              また、出品をもちまして
              = link_to "加盟店規約", "#"
              に同意したことになります。
        = f.submit "変更する", {id: "item_submit"}
        = link_to "キャンセル", :back, class: "page_back"
    .new_item_page_container_bottom
      .bottom__attention
        %span プライバシーポリシー
        %span メルカリ利用規約
        %span 特定商取引に関する表記
      .bottom__logo
        = link_to root_path do
          = image_tag 'logo-gray.svg'
      .bottom__copy_light
        &copy;2019 Mercari
  = render "shared/new_item_button"

app/views/items/index.html.haml
.top_page
  = render "shared/header"
  .top_page_info_area
    = image_tag "banner-camp.jpg", class: "top_page_info_area__banner"
    = image_tag "banner-camp.jpg", class: "top_page_info_area__banner"
    = image_tag "banner-camp.jpg", class: "top_page_info_area__banner"
    = image_tag "banner-camp.jpg", class: "top_page_info_area__banner"
    = image_tag "banner-camp.jpg", class: "top_page_info_area__banner"
  .top_page_main
    = render "shared/top_page_main"
  = render "shared/footer"
  = render "shared/new_item_button"

app/views/items/new.html.haml
.new_item_page
  .new_item_page_container
    .new_item_page_container_top
      .new_item_page_container_top__img
        = link_to root_path do
          = image_tag "logo.svg"
    = form_with model: @item, url: items_path, class: "new_item_page_container_main" ,method: :post , local: true do |f|
      .new_item_page_container_main_title
        商品の情報を入力
      .new_item_page_container_main_item_image
        = render "shared/error_messages" , model: f.object
        %p.new_item_page_container_main_label
          出品画像
          %span.required
            必須
        %p.desc 最大10枚までアップロードできます。
        .new_item_page_container_main_item_image_area
          .top_area.prepend_area
            .image_file_area
              %p 
                ドラッグアンドドロップ
                %br
                もしくはクリックをしてアップロード
              = f.file_field :images, multiple: true, id: "upload_file", class: "upload_files", data:{id: "1"}
              = f.hidden_field :file, class: "item_images_hidden", multiple: true
          .under_area.prepend_area
            .image_file_area
              %p 
                ドラッグアンドドロップ
                %br
                もしくはクリックをしてアップロード
      
      .new_item_page_container_main_carrierwave_image
        %p.new_item_page_container_main_label
          Carrirwaveの場合
        
        = f.fields_for :item_images do |i|
          = i.file_field :src
          
      .new_item_page_container_main_item_description
        %p.new_item_page_container_main_label
          商品名 
          %span.required
            必須
        = f.text_field :name, {placeholder: "商品名 (必須40文字まで)", maxlength: "40"}
        %p.new_item_page_container_main_label
          商品の説明
          %span.required
            必須
        = f.text_area :description, {maxlength: "1000",  placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"}
      .new_item_page_container_main_item_detail
        .left_content
          商品の詳細
        .right_content
          %p.new_item_page_container_main_label
            カテゴリ
            %span.required
              必須
          .select_box.category1.new_category1
            = f.select :category1, options_from_collection_for_select(Category.where('id < 14'), :id, :name)
            = fa_icon "angle-down"
          .select_box.category2
            = f.select :category2, []
            = fa_icon "angle-down"
          .select_box.category3
            = f.select :category_id, []
            = fa_icon "angle-down"
          #select_size
            %p.new_item_page_container_main_label.select_label
              サイズ
              %span.required
                必須
            .select_box
              = f.select :size, [["---", ""], ["XXS以下", "XXS以下"],["XS(SS)", "XS(SS)"], ["S", "S"], ["M", "M"], ["L", "L"], ["XL(LL)", "XL(LL)"], ["2XL(3L)", "2XL(3L)"], ["3XL(4L)", "3XL(4L)"], ["4XL(5L)以上", "4XL(5L)以上"], ["FREE SIZE", "FREE SIZE"]]
              = fa_icon "angle-down"
          #input_bland
            %p.new_item_page_container_main_label.select_label
              ブランド
              %span.optional
                任意
            .input_box
              = f.text_field :bland, {placeholder: "例) シャネル"}
          %p.new_item_page_container_main_label.select_label
            商品の状態
            %span.required
              必須
          .select_box
            = f.select :status, [["---", ""], ["新品", "新品"],["未使用に近い", "未使用に近い"],["目立った傷や汚れなし", "目立った傷や汚れなし"], ["やや傷や汚れあり", "やや傷や汚れあり"], ["全体的に状態が悪い", "全体的に状態が悪い"]]
            = fa_icon "angle-down"
      .new_item_page_container_main_item_delivary
        .left_content
          配送について
        .right_content
          %p.new_item_page_container_main_label
            配送料の負担
            %span.required
              必須
          .select_box
            = f.select :delivery_burden, [["---", ""], ["送料込み(出品者負担)", "送料込み(出品者負担)"],["着払い(購入者負担)", "着払い(購入者負担)"]]
            = fa_icon "angle-down"
          %p.new_item_page_container_main_label.delivery_method_select_label
            配送の方法
            %span.required
              必須
          .select_box.delivery_method_select
            = f.select :delivery_method, [], id: "delivery_method"
            = fa_icon "angle-down"
          %p.new_item_page_container_main_label
            発送元の地域
            %span.required
              必須
          .select_box

            = f.select :delivery_prefecture, options_from_collection_for_select(Prefecture.all, :name, :name)
            = fa_icon "angle-down"
          %p.new_item_page_container_main_label
            発送までの日数
            %span.required
              必須
          .select_box
            = f.select :delivery_time, [["---", ""], ["1~2日", "1~2日"],["3~4日", "3~4日"],["4~7日", "4~7日"]]
            = fa_icon "angle-down"
      .new_item_page_container_main_item_price
        .left_content
          販売価格
          %span (300〜9,999,999)
        .right_content
          .input_price
            %p.new_item_page_container_main_label
              価格
              %span.required
                必須
            .input_price__area
              ¥
              = f.text_field :price, {id: "price", placeholder: "例）300", maxlength: "7", value: ""}
          .sales_fee
            %p 販売手数料(10%)
            %p.sales_fee__computed -
          .sales_benefit
            %p 販売利益
            %p.sales_benefit__computed -
      .new_item_page_container_main_submit
        %p.new_item_page_container_main_submit__attension
          = link_to "禁止されている出品", "#"
          、
          = link_to "行為", "#"
          を必ずご確認ください。
          %br
            またブランド品でシリアルナンバー等がある場合はご記載ください。
            = link_to "偽ブランドの販売", "#"
            は犯罪であり処罰される可能性があります。
            %br 
              また、出品をもちまして
              = link_to "加盟店規約", "#"
              に同意したことになります。
        = f.submit "出品する", {id: "item_submit"}
        = link_to "もどる", :back, class: "page_back"
    .new_item_page_container_bottom
      .bottom__attention
        %span プライバシーポリシー
        %span メルカリ利用規約
        %span 特定商取引に関する表記
      .bottom__logo
        = link_to root_path do
          = image_tag 'logo-gray.svg'
      .bottom__copy_light
        &copy;2019 Mercari
  = render "shared/new_item_button"

app/views/items/search.html.haml
.item_search_page
  = render "shared/header"
  .container
    .left-column
      .incremental-search-panel
        = form_with url: incremental_items_path ,method: :get ,class: "header_search" do |f| 
          = f.text_field :keyword ,{class: "header_search__input incremental", placeholder: "インクリメンタルサーチ！"}
      .detail-search-panel
        = search_form_for @q, url: "ransack" do |f|
          詳細検索
          .detail-search-panel_section
            = fa_icon "plus"
            キーワードを追加する
            = f.search_field :name_cont, placeholder: "例) コート",class: "ransack_input_panel"
          -# .detail-search-panel_section
          -#   = fa_icon "align-justify"
          -#   カテゴリーを選択する
          -#   = f.search_field :name_cont
          -#   = f.collection_select :category_id_eq, @category, :id, :name, :include_blank => '指定なし'
          .detail-search-panel_section
            .search_btn
              .search_btn_reset
                クリア
              .search_btn_submit
                = f.submit "完了"
    .right-column
      .main_block
        .main_block__text
          %h2
            %span.main_block__text__keyword
              = "#{@keyword}の検索結果"
          %p
            %span.main_block__text__hit_count
              = "#{@items.length}件表示"
        .main_block__item
          = render @items
  = render "shared/footer"
  = render "shared/new_item_button"

app/views/items/show.html.haml
.detail_item{data: {item: {id: @item.id}}}
  = render 'shared/header'
  .bread
    %span 
      - breadcrumb :detail_item, @item
      = breadcrumbs separator: " #{content_tag(:i, '', class:'fa fa-chevron-right')} "
  .main
    .main_header
      %h2 
        = @item.name
    .main_item-detail
      - if @item.buy_history.present?
        .main_item-detail_images.item_soldout__parent
          .main_item-detail_images__big.item_soldout__children
            = image_tag @item.images[0], id: "big_image"
          %ul.main_item-detail_images__small
            - @item.images.each do |image|
              %li
                = image_tag image, class: "small_image"
      - else
        .main_item-detail_images
          .main_item-detail_images__big
            = image_tag @item.images[0], id: "big_image"
          %ul.main_item-detail_images__small
            - @item.images.each do |image|
              %li
                = image_tag image, class: "small_image"
      .main_item-detail_table
        .main_item-detail_table__row
          .cell
            出品者
          .cell
            .listing-person 
              .listing-person_name
                = @item.user.nickname
              .listing-person_evelute-box
                .listing-person_evelute-box--icon-good
                  = image_tag "face-grin.png"
                  %p 151
                .listing-person_evelute-box--icon-soso
                  = image_tag "face-mef.png"
                  %p 151
                .listing-person_evelute-box--icon-bad
                  = image_tag "face-frown.png"
                  %p 151
        .main_item-detail_table__row
          .cell
            カテゴリー
          .cell
            - if @item.category_id != 0
              = link_to "#" do
                = @item.category.parent.parent.name
                %br
                >
                = @item.category.parent.name
                %br
                >
                = @item.category.name
            - else 
              カテゴリ未登録
        .main_item-detail_table__row
          .cell
            ブランド
          .cell
            Maeda Shoppers Team
        - if @item.size.present?
          .main_item-detail_table__row
            .cell
              商品のサイズ
            .cell
              = @item.size
        .main_item-detail_table__row
          .cell
            商品の状態
          .cell
            = @item.status
        .main_item-detail_table__row
          .cell
            配送料の負担
          .cell
            = @item.delivery_burden
        .main_item-detail_table__row
          .cell
            配送の方法
          .cell
            = @item.delivery_method
        .main_item-detail_table__row
          .cell
            配送元地域
          .cell#prefecture
            = @item.delivery_prefecture
        .main_item-detail_table__row
          .cell
            発送日の目安
          .cell
            = @item.delivery_time
    .main_price
      .main_price__display
        = @item.price
      .main_price__delivery_fee
        %span.tax (税込)
        %span.fee
          - if @item.delivery_burden == "送料込み(出品者負担)"
            送料込み
          - else 
            送料別
    - if user_signed_in? && @item.user.id != current_user.id
      - if @item.buy_history.present?
        .main_purchase_button.main_purchase_button--disable 
          売り切れました
      - else
        .main_balloon_area
          .main_stock_money
            残高 ¥925をお持ちです
            .main_stock_money__triangle
          = link_to "購入画面に進む", new_item_buy_history_path(@item), class: "main_purchase_button"
    .main_item_description
      .main_item_description__top
        = @item.description
      .main_item_description__bottom
        .main_item_description__bottom--right
          .goob_button
            = fa_icon "heart-o"
            いいね!
            8
          .notice_button
            = fa_icon "flag"
            不適切な商品の報告
        = link_to "#", class: "safty_effort_link" do
          = fa_icon "lock"
          安心、安全への取り組み
  - if user_signed_in? && @item.user.id == current_user.id
    .preview_page_box
      = link_to "商品の編集", edit_item_path, class: "preview_page_box__edit"
      or
      .preview_page_box__suspend
        商品の出品を一旦停止する
      = link_to "この商品を削除する", item_path, class: "preview_page_box__destroy", method: :delete
  .user_comments
    .user_comments__bix
      .user_icon
        = image_tag "member_photo_noimage_thumb.png"
      .user_name
        %p John
      .user_comment
        %p 初めまして値下げ可能ですか？
        .user_comment__timestamp
          %span
            = fa_icon "clock-o"
            6 時間前
    - @comments.each do |comment|
      .user_comments__bix
        .user_icon
          = image_tag "member_photo_noimage_thumb.png"
        .user_name
          %p 
            = comment.user.nickname
        .user_comment
          %p 
            = comment.text
          .user_comment__timestamp
            %span
              = fa_icon "clock-o"
              = comment.created_at
    .user_comments_form
      = form_with( model: [@item, @comment]) do |f|
        = f.text_field :text
        = f.submit
    .adjacent_item
      .return_item
        =link_to "水着"
        =fa_icon "chevron-left"
      .next_item
        =link_to "ホテルキー風キーホルダー"
        =fa_icon "chevron-right"
  .sns_login
    .sns_login__box
      .sns_login__box--icon-facebook
        = fa_icon "facebook-square"
      .sns_login__box--icon-twitter
        = fa_icon "twitter-square"
      .sns_login__box--icon-pinterest
        = fa_icon "pinterest-square"
  .other_listing
    .pick_up_category_ladies.main_block_new_items
      %h2
        = link_to "#{@item.user.nickname}さんのその他の出品", "#"
      .main_block_new_items_area
        = render @item.user.items
  .item_listing
    .pick_up_category_ladies.main_block_new_items
      %h2
        = link_to "レディース 新着アイテム", "#"
      .main_block_new_items_area
        = render @items
  = render "shared/footer"